name: Build and Publish image to Docker Hub

on: 
    [workflow_dispatch]
   
jobs: 
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: build api image
              run: docker build ./api/ -t nathula132/devops-qr-code-api:latest

            - name: build frontend image
              run: docker build ./front-end-nextjs/ -t nathula132/devops-qr-code-frontend:latest

            - name: push images to docker hub
              run: |
                docker login -u nathula132 -p ${{ secrets.DOCKER_HUB_TOKEN }}
                docker push nathula132/devops-qr-code-api:latest
                docker push nathula132/devops-qr-code-frontend:latest